name: Node.js CI & Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - name: Publish to NPM
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          npm version patch -m "Upgrade version [skip ci]"
          git push
          git push --tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
